name: "JS Weekly Trending"

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "5 2 1 * *"

jobs:
  trending:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ["python", "javascript", "typescript"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Trending Repo
        uses: luxass/action-trending@v2.1.1
        with:
          date: weekly # daily, weekly, monthly (default: daily)
          spoken: da
          language: ${{matrix.language}}
          output: "{pwd}/dictionaries/{language}/{unix}.json"
      - name: Commit Files
        run: |
          ls -al
          git add .
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m "Update"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: ${{github.ref}}
